import type { AssistantIngredient, ProductKnowledgeBlueprint } from "@/lib/assistant/types";

const PAGE = (handle: string) => `https://blackmarketlabs.com/products/${handle}`;
const LABEL = (file: string) => `/assets/${file}`;
const GUIDE_PAGES: Record<string, string> = {
  "cuts-thermogenic-pre-workout": "1–2",
  "tone-weight-loss-pre-workout": "4–5",
  "bulk-testosterone-pre-workout": "6–7",
  "nootropic-high-focus-pre-workout": "2–3",
  "underground-high-stimulant": "7–9",
  "defy-hyper-stimulant": "12–14",
  "rule-hyper-focus": "14–15",
  "nitricoxide-stim-free-pre-workout": "9–10",
  "pump-hyper-pump-pre-workout": "15–16",
  "cuts-diamond-ultra-thermogenic": "11–12",
  "cuts-pump-thermogenic-liquid-glycerol": "16–17",
};
const prohibitedClaims = [
  "diagnoses or treats a medical condition",
  "guarantees weight loss, muscle gain, or a health outcome",
  "states that a product is medically safe for a particular person",
];

function ingredient(
  name: string,
  amount: number | undefined,
  unit: AssistantIngredient["unit"],
  roles: AssistantIngredient["roles"],
  sourceIds: string[],
  disclosure: AssistantIngredient["disclosure"] = amount === undefined ? "official-highlight" : "exact",
  servingBasis = "full serving",
): AssistantIngredient {
  return {
    name,
    normalizedName: normalizeIngredient(name),
    ...(amount === undefined ? {} : { amount }),
    ...(unit === undefined ? {} : { unit }),
    servingBasis,
    disclosure,
    roles,
    verified: true,
    sourceIds,
  };
}

function normalizeIngredient(value: string): string {
  return value
    .toLowerCase()
    .replace(/[™®]/g, "")
    .replace(/\([^)]*\)/g, " ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function sources(
  productId: string,
  handle: string,
  labelPath: string,
  labelNote = "Supplement Facts image currently used by the wholesale portal.",
) {
  const guidePages = GUIDE_PAGES[productId];
  return [
    { id: `${productId}:catalog`, type: "catalog-record" as const, location: "/catalog-data.json" },
    { id: `${productId}:official`, type: "official-product-page" as const, location: PAGE(handle) },
    { id: `${productId}:label`, type: "supplement-facts-image" as const, location: LABEL(labelPath), note: labelNote },
    ...(guidePages ? [{
      id: `${productId}:guide`,
      type: "product-guide" as const,
      location: `BLACKMARKETLABS Pre-Workout Product Guide (2026-07-27), pages ${guidePages}`,
      note: "Owner-supplied authoritative product guide.",
    }] : []),
  ];
}

export const PRODUCT_KNOWLEDGE: ProductKnowledgeBlueprint[] = [
  {
    productId: "cuts-thermogenic-pre-workout",
    shortName: "CUTS",
    aliases: ["cuts", "cuts pre workout", "cuts thermogenic"],
    purpose: "The core thermogenic pre-workout in the line, positioned around consistent energy, performance, and focus.",
    retailerPitch: "The broad, established CUTS option for stores that want a recognizable thermogenic pre-workout at a $49.99 MAP.",
    bestFor: ["A broad thermogenic-pre-workout shelf", "Customers seeking a 300 mg caffeine pre-workout"],
    notIdealFor: ["A stimulant-free request", "Buyers who require every active ingredient to have an individually disclosed dosage"],
    keyDifferentiators: ["300 mg caffeine anhydrous", "Seven represented flavors", "Long-running core CUTS positioning"],
    goals: ["cutting", "energy", "focus", "daily"],
    formula: {
      servingSize: "1 scoop (8 g)",
      servingsPerContainer: 30,
      totalCaffeineMg: 300,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Vitamin C", 50, "mg", ["vitamin"], ["cuts-thermogenic-pre-workout:guide"]),
        ingredient("Chromium", 144, "mcg", ["mineral"], ["cuts-thermogenic-pre-workout:guide"]),
        ingredient("Sodium", 20, "mg", ["mineral", "hydration"], ["cuts-thermogenic-pre-workout:guide"]),
        ingredient("Beta-Alanine", 3.2, "g", ["performance"], ["cuts-thermogenic-pre-workout:guide"]),
        ingredient("L-Carnitine Tartrate", 1, "g", ["thermogenic", "performance"], ["cuts-thermogenic-pre-workout:guide"]),
        ingredient("Agmatine Sulfate", undefined, undefined, ["pump"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Acetyl L-Carnitine HCl", undefined, undefined, ["focus", "thermogenic"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant", "energy"], ["cuts-thermogenic-pre-workout:label"]),
        ingredient("Choline Bitartrate", undefined, undefined, ["focus"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Raspberry Ketone", undefined, undefined, ["thermogenic"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Bitter Orange Extract", undefined, undefined, ["stimulant", "thermogenic"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Mucuna Pruriens", undefined, undefined, ["focus"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Evodiamine", undefined, undefined, ["thermogenic"], ["cuts-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Chromium Picolinate", undefined, undefined, ["mineral"], ["cuts-thermogenic-pre-workout:guide"], "listed-in-blend"),
      ],
      verification: "verified",
      reviewNotes: ["The label discloses a 5,676 mg proprietary blend; most individual ingredient dosages are not disclosed."],
    },
    relationships: {
      commonlyComparedWith: ["cuts-natural-thermogenic-pre-workout", "cuts-diamond-ultra-thermogenic", "tone-weight-loss-pre-workout"],
      complements: ["cuts-pump-thermogenic-liquid-glycerol", "l-citrulline-raw"],
      substitutes: ["cuts-natural-thermogenic-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("cuts-thermogenic-pre-workout", "cuts-thermogenic-pre-workout", "site-images/cuts-thermogenic-pre-workout-panel-cuts-fruitpunch-supfact.jpg"),
    verification: "verified",
  },
  {
    productId: "cuts-natural-thermogenic-pre-workout",
    shortName: "CUTS Natural",
    aliases: ["cuts natural", "natural cuts"],
    purpose: "The core CUTS thermogenic formula positioned with natural flavors, colors, and sweeteners.",
    retailerPitch: "A CUTS alternative for label-conscious shoppers who still want the established 300 mg thermogenic-pre-workout positioning.",
    bestFor: ["Stores asked for a naturally flavored and sweetened CUTS option", "Customers seeking 300 mg caffeine"],
    notIdealFor: ["A stimulant-free request", "A fully transparent formula request"],
    keyDifferentiators: ["Natural flavor, color, and sweetener positioning", "300 mg caffeine anhydrous"],
    goals: ["cutting", "energy", "focus", "daily"],
    formula: {
      servingSize: "1 scoop (7.9 g)",
      servingsPerContainer: 30,
      totalCaffeineMg: 300,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Beta-Alanine", undefined, undefined, ["performance"], ["cuts-natural-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("L-Carnitine Tartrate", undefined, undefined, ["thermogenic", "performance"], ["cuts-natural-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Agmatine Sulfate", undefined, undefined, ["pump"], ["cuts-natural-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Acetyl L-Carnitine HCl", undefined, undefined, ["focus", "thermogenic"], ["cuts-natural-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["cuts-natural-thermogenic-pre-workout:label"]),
        ingredient("Bitter Orange Extract", undefined, undefined, ["stimulant", "thermogenic"], ["cuts-natural-thermogenic-pre-workout:label"], "listed-in-blend"),
        ingredient("Mucuna Pruriens", undefined, undefined, ["focus"], ["cuts-natural-thermogenic-pre-workout:label"], "listed-in-blend"),
      ],
      verification: "needs-review",
      reviewNotes: ["The label discloses a 5,626 mg proprietary blend; most individual ingredient dosages are not disclosed."],
    },
    relationships: {
      commonlyComparedWith: ["cuts-thermogenic-pre-workout", "cuts-diamond-ultra-thermogenic"],
      complements: ["cuts-pump-thermogenic-liquid-glycerol"],
      substitutes: ["cuts-thermogenic-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("cuts-natural-thermogenic-pre-workout", "cuts-natural", "site-images/cuts-natural-thermogenic-pre-workout-panel-cutsnat-supfacts.jpg"),
    verification: "verified",
  },
  {
    productId: "cuts-diamond-ultra-thermogenic",
    shortName: "CUTS Diamond",
    aliases: ["cuts diamond", "diamond cuts", "cuts ultra"],
    purpose: "The strongest thermogenic pre-workout positioning in the CUTS family, with a transparent formula and added pump support.",
    retailerPitch: "The premium CUTS step-up at a $59.99 MAP for customers who want a more disclosed, higher-feature formula.",
    bestFor: ["Experienced thermogenic-pre-workout customers", "A premium CUTS upsell", "Customers who value transparent dosages"],
    notIdealFor: ["A stimulant-free request", "A lower-price opening SKU"],
    keyDifferentiators: ["300 mg caffeine", "5 g L-Citrulline", "3.2 g Beta-Alanine", "Three disclosed forms of L-Carnitine"],
    goals: ["cutting", "energy", "focus", "pump"],
    formula: {
      servingSize: "1 scoop (13.63 g)",
      servingsPerContainer: 25,
      totalCaffeineMg: 300,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("L-Citrulline", 5, "g", ["pump", "performance"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("Beta-Alanine", 3.2, "g", ["performance"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("L-Carnitine Tartrate", 1.5, "g", ["thermogenic", "performance"], ["cuts-diamond-ultra-thermogenic:guide"]),
        ingredient("Acetyl L-Carnitine HCl", 500, "mg", ["focus", "thermogenic"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("L-Carnitine Fumarate", 500, "mg", ["thermogenic", "performance"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("Choline Bitartrate", 600, "mg", ["focus"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("Bitter Orange Extract", 150, "mg", ["stimulant", "thermogenic"], ["cuts-diamond-ultra-thermogenic:guide"]),
        ingredient("Mucuna Pruriens", 100, "mg", ["focus"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("Evodiamine", 50, "mg", ["thermogenic"], ["cuts-diamond-ultra-thermogenic:guide"]),
        ingredient("Grains of Paradise", 40, "mg", ["thermogenic"], ["cuts-diamond-ultra-thermogenic:guide"]),
        ingredient("ProGBB", 30, "mg", ["thermogenic"], ["cuts-diamond-ultra-thermogenic:label"]),
        ingredient("Chromium Picolinate", 3.6, "mg", ["mineral"], ["cuts-diamond-ultra-thermogenic:guide"]),
        ingredient("BioPerine", 5, "mg", ["other"], ["cuts-diamond-ultra-thermogenic:label"]),
      ],
      verification: "verified",
      reviewNotes: ["Grape Limeade has a separate facts image and remains linked as a variant-specific source."],
    },
    relationships: {
      commonlyComparedWith: ["cuts-thermogenic-pre-workout", "scorch-ultra-thermogenic"],
      complements: ["cuts-pump-thermogenic-liquid-glycerol"],
      substitutes: ["scorch-ultra-thermogenic", "cuts-thermogenic-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("cuts-diamond-ultra-thermogenic", "cuts-diamond-thermogenic-pre-workout", "site-images/cuts-diamond-ultra-thermogenic-panel-cutsdiamond-watmelon-supfact.png"),
    verification: "verified",
  },
  {
    productId: "cuts-pump-thermogenic-liquid-glycerol",
    shortName: "CUTS PUMP",
    aliases: ["cuts pump", "cuts glycerol", "liquid glycerol"],
    purpose: "A caffeine-free liquid glycerol and L-Carnitine product positioned for hydration, pump, and stackability.",
    retailerPitch: "An easy add-on sale for CUTS buyers who want a stimulant-free liquid pump and hydration product.",
    bestFor: ["Stacking with a powdered pre-workout", "A caffeine-free pump request", "Liquid-format shoppers"],
    notIdealFor: ["Customers asking for stimulant energy"],
    keyDifferentiators: ["Liquid format", "20 g glycerol per full cap", "Caffeine free", "Half-cap or full-cap serving"],
    goals: ["pump", "hydration", "stim-free", "cutting"],
    formula: {
      servingSize: "1 cap (30 servings) or 1/2 cap (60 servings)",
      servingsPerContainer: 30,
      totalCaffeineMg: 0,
      caffeineServingBasis: "1 full cap",
      stimulantFree: true,
      ingredients: [
        ingredient("Glycerol", 20, "g", ["hydration", "pump"], ["cuts-pump-thermogenic-liquid-glycerol:label"]),
        ingredient("L-Carnitine", 1500, "mg", ["thermogenic", "performance"], ["cuts-pump-thermogenic-liquid-glycerol:label"]),
        ingredient("L-Arginine AKG", 1000, "mg", ["pump"], ["cuts-pump-thermogenic-liquid-glycerol:label"]),
        ingredient("Pink Himalayan Salt", 500, "mg", ["hydration", "mineral"], ["cuts-pump-thermogenic-liquid-glycerol:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["pump-hyper-pump-pre-workout", "nitricoxide-stim-free-pre-workout"],
      complements: ["cuts-thermogenic-pre-workout", "cuts-diamond-ultra-thermogenic"],
      substitutes: ["pump-hyper-pump-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("cuts-pump-thermogenic-liquid-glycerol", "cuts-pump-thermogenic-glycerol", "site-images/cuts-pump-thermogenic-liquid-glycerol-panel-cutsliquid-sourgum-ingred.png"),
    verification: "verified",
  },
  {
    productId: "cuts-pills-thermogenic-capsules",
    shortName: "CUTS PILLS",
    aliases: ["cuts pills", "cuts capsules", "thermogenic pills"],
    purpose: "A capsule-format thermogenic and energy product for customers who do not want a powdered pre-workout.",
    retailerPitch: "The convenient CUTS capsule option with a high MAP-to-wholesale margin and no flavor decision.",
    bestFor: ["Capsule-format shoppers", "A simple single-SKU CUTS add-on"],
    notIdealFor: ["A stimulant-free request", "Customers asking for a confirmed total-caffeine number until the guarana contribution is verified"],
    keyDifferentiators: ["Capsule delivery", "Single no-flavor SKU", "Caffeine, guarana, and theobromine combination"],
    goals: ["cutting", "energy", "focus"],
    formula: {
      servingSize: "4 capsules",
      servingsPerContainer: 30,
      stimulantFree: false,
      ingredients: [
        ingredient("L-Carnitine Fumarate", 750, "mg", ["thermogenic", "performance"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Dandelion Extract", 500, "mg", ["thermogenic"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Beta Phenylethylamine HCl", 200, "mg", ["focus", "stimulant"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Caffeine Anhydrous", 175, "mg", ["stimulant"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Guarana Extract", 100, "mg", ["stimulant"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("L-Theanine", 100, "mg", ["focus"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Theobromine", 100, "mg", ["stimulant"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Bitter Orange Extract", 50, "mg", ["stimulant", "thermogenic"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Grains of Paradise", 40, "mg", ["thermogenic"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("ProGBB", 40, "mg", ["thermogenic"], ["cuts-pills-thermogenic-capsules:label"]),
        ingredient("Alpha Yohimbine", 1, "mg", ["stimulant", "thermogenic"], ["cuts-pills-thermogenic-capsules:label"]),
      ],
      verification: "needs-review",
      reviewNotes: ["The label confirms 175 mg caffeine anhydrous, but total caffeine including guarana is not confirmed."],
    },
    relationships: {
      commonlyComparedWith: ["cuts-thermogenic-pre-workout", "bulk-pills-testosterone-capsules"],
      complements: [],
      substitutes: ["cuts-thermogenic-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("cuts-pills-thermogenic-capsules", "cuts-thermogenic-pills", "products/cuts-pills-thermogenic-capsules-panel.png"),
    verification: "needs-review",
  },
  {
    productId: "cuts-heat-stim-free-thermogenic",
    shortName: "CUTS HEAT",
    aliases: ["cuts heat", "heat stim free", "stim free thermogenic"],
    purpose: "A stimulant-free thermogenic formula positioned for daily consistency and stackability.",
    retailerPitch: "The CUTS option for buyers who want thermogenic positioning without caffeine.",
    bestFor: ["Stimulant-free thermogenic requests", "Stacking with a separate pre-workout"],
    notIdealFor: ["Customers who specifically want stimulant energy"],
    keyDifferentiators: ["No disclosed caffeine", "L-Carnitine and taurine", "Stackable positioning"],
    goals: ["cutting", "focus", "stim-free", "daily"],
    formula: {
      servingSize: "1 scoop (7 g)",
      servingsPerContainer: 30,
      totalCaffeineMg: 0,
      caffeineServingBasis: "1 scoop",
      stimulantFree: true,
      ingredients: [
        ingredient("L-Carnitine L-Tartrate", 1000, "mg", ["thermogenic", "performance"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("Taurine", 1000, "mg", ["hydration", "performance"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("Metabolyte", 900, "mg", ["hydration"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("L-Tyrosine", 400, "mg", ["focus"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("Bitter Orange Extract", 160, "mg", ["thermogenic"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("ProGBB", 30, "mg", ["thermogenic"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("Grains of Paradise", 30, "mg", ["thermogenic"], ["cuts-heat-stim-free-thermogenic:label"]),
        ingredient("BioPerine", 5, "mg", ["other"], ["cuts-heat-stim-free-thermogenic:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["cuts-thermogenic-pre-workout", "nitricoxide-stim-free-pre-workout"],
      complements: ["bump-laser-focus-nootropic"],
      substitutes: ["cuts-pump-thermogenic-liquid-glycerol"],
    },
    prohibitedClaims,
    sources: sources("cuts-heat-stim-free-thermogenic", "cuts-heat-stim-free-thermogenic", "site-images/cuts-heat-stim-free-thermogenic-panel-cuts-heat-wm-supfact.jpg"),
    verification: "verified",
  },
  {
    productId: "scorch-ultra-thermogenic",
    shortName: "SCORCH",
    aliases: ["scorch", "scorch ultra", "ultra thermogenic"],
    purpose: "A premium, high-caffeine thermogenic pre-workout with substantial disclosed pump support.",
    retailerPitch: "A high-intensity thermogenic choice for experienced stimulant buyers at a premium MAP.",
    bestFor: ["Experienced stimulant users", "Customers seeking thermogenic positioning with 8 g L-Citrulline"],
    notIdealFor: ["Stimulant-sensitive shoppers", "A daily low-stimulant request"],
    keyDifferentiators: ["450 mg official total caffeine", "8 g L-Citrulline", "20 servings", "BLACKMARKET and Anabolic Warfare collaboration"],
    goals: ["cutting", "energy", "pump", "focus"],
    formula: {
      servingSize: "1 scoop (19.2 g)",
      servingsPerContainer: 20,
      totalCaffeineMg: 450,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("L-Citrulline", 8, "g", ["pump", "performance"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Beta-Alanine", 3.2, "g", ["performance"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Acetyl L-Carnitine HCl", 500, "mg", ["focus", "thermogenic"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Dandelion Extract", 500, "mg", ["thermogenic"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Choline Bitartrate", 300, "mg", ["focus"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Caffeine Anhydrous", 350, "mg", ["stimulant"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Natural Caffeine", 100, "mg", ["stimulant"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Bitter Orange Extract", 130, "mg", ["stimulant", "thermogenic"], ["scorch-ultra-thermogenic:label"]),
        ingredient("Mucuna Pruriens", 75, "mg", ["focus"], ["scorch-ultra-thermogenic:label"]),
        ingredient("ProGBB", 20, "mg", ["thermogenic"], ["scorch-ultra-thermogenic:label"]),
        ingredient("BioPerine", 5, "mg", ["other"], ["scorch-ultra-thermogenic:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["cuts-diamond-ultra-thermogenic", "defy-hyper-stimulant"],
      complements: [],
      substitutes: ["cuts-diamond-ultra-thermogenic"],
    },
    prohibitedClaims,
    sources: sources("scorch-ultra-thermogenic", "scorch-ultra-thermogenic-pre-workout", "site-images/scorch-ultra-thermogenic-panel-scorch-killshot-ingrd.png"),
    verification: "verified",
  },
  {
    productId: "tone-weight-loss-pre-workout",
    shortName: "TONE",
    aliases: ["tone", "tone weight loss", "tone pre workout"],
    purpose: "A thermogenic pre-workout positioned with antioxidants, sustained energy, and focus.",
    retailerPitch: "A distinct thermogenic shelf option for stores that want a different ingredient story than the CUTS family.",
    bestFor: ["Thermogenic assortment variety", "Customers seeking 300 mg caffeine"],
    notIdealFor: ["A stimulant-free request", "A fully transparent formula request"],
    keyDifferentiators: ["300 mg caffeine", "CLA and antioxidant positioning", "Thermogenic category alternative to CUTS"],
    goals: ["cutting", "energy", "focus"],
    formula: {
      servingSize: "1 scoop (9 g)",
      servingsPerContainer: 30,
      totalCaffeineMg: 300,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("CLA", undefined, undefined, ["thermogenic"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Beta-Alanine", undefined, undefined, ["performance"], ["tone-weight-loss-pre-workout:label"], "listed-in-blend"),
        ingredient("Theobromine", undefined, undefined, ["stimulant"], ["tone-weight-loss-pre-workout:label"], "listed-in-blend"),
        ingredient("L-Carnitine Tartrate", undefined, undefined, ["thermogenic", "performance"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("L-Citrulline Malate", undefined, undefined, ["pump"], ["tone-weight-loss-pre-workout:label"], "listed-in-blend"),
        ingredient("Bitter Orange Extract", undefined, undefined, ["stimulant", "thermogenic"], ["tone-weight-loss-pre-workout:label"], "listed-in-blend"),
        ingredient("L-Theanine", undefined, undefined, ["focus"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Raspberry Ketone", undefined, undefined, ["thermogenic"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Green Coffee Bean Extract", undefined, undefined, ["thermogenic"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Green Tea Extract", undefined, undefined, ["thermogenic"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Blepharococcus", undefined, undefined, ["other"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Pomegranate Extract", undefined, undefined, ["other"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Acai Berry Extract", undefined, undefined, ["other"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Blueberry Extract", undefined, undefined, ["other"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Black Pepper Extract", undefined, undefined, ["other"], ["tone-weight-loss-pre-workout:guide"], "listed-in-blend"),
        ingredient("Vitamin B1", 1.5, "mg", ["vitamin"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Biotin", 30, "mcg", ["vitamin"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Vitamin B6", 2, "mg", ["vitamin"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Vitamin B12", 6.8, "mcg", ["vitamin"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Folate", 435, "mcg", ["vitamin"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Chromium", 116, "mcg", ["mineral"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Sodium", 10, "mg", ["mineral", "hydration"], ["tone-weight-loss-pre-workout:guide"]),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["tone-weight-loss-pre-workout:label"]),
      ],
      verification: "verified",
      reviewNotes: ["The guide identifies three proprietary blend totals; only individually printed amounts are presented as exact."],
    },
    relationships: {
      commonlyComparedWith: ["cuts-thermogenic-pre-workout", "cuts-natural-thermogenic-pre-workout"],
      complements: ["l-citrulline-raw"],
      substitutes: ["cuts-thermogenic-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("tone-weight-loss-pre-workout", "tone-weight-loss-pre-workout", "site-images/tone-weight-loss-pre-workout-panel-tonerl-crop.png"),
    verification: "verified",
  },
  {
    productId: "bulk-testosterone-pre-workout",
    shortName: "BULK",
    aliases: ["bulk", "bulk pre workout", "bulk strength"],
    purpose: "The original BULK strength-oriented pre-workout, positioned around power output, energy, focus, and natural testosterone support.",
    retailerPitch: "The lower-MAP, time-tested BULK option for broad strength-category placement.",
    bestFor: ["A core strength pre-workout SKU", "Customers seeking creatine and 300 mg caffeine"],
    notIdealFor: ["A stimulant-free request", "Buyers requiring all exact ingredient dosages"],
    keyDifferentiators: ["Contains Creatine Monohydrate", "300 mg caffeine", "$49.99 MAP", "Original BULK formula positioning"],
    goals: ["strength", "energy", "focus", "recovery"],
    formula: {
      servingSize: "1 scoop (11 g)",
      servingsPerContainer: 30,
      totalCaffeineMg: 300,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Beta-Alanine", undefined, undefined, ["performance"], ["bulk-testosterone-pre-workout:official"]),
        ingredient("D-Aspartic Acid", undefined, undefined, ["strength"], ["bulk-testosterone-pre-workout:official"]),
        ingredient("Creatine Monohydrate", undefined, undefined, ["strength", "performance"], ["bulk-testosterone-pre-workout:official"]),
        ingredient("Betaine Anhydrous", undefined, undefined, ["strength", "performance"], ["bulk-testosterone-pre-workout:official"]),
        ingredient("Agmatine Sulfate", undefined, undefined, ["pump"], ["bulk-testosterone-pre-workout:guide"], "listed-in-blend"),
        ingredient("Bitter Orange Extract", undefined, undefined, ["stimulant"], ["bulk-testosterone-pre-workout:official"]),
        ingredient("Mucuna Pruriens", undefined, undefined, ["focus"], ["bulk-testosterone-pre-workout:official"]),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["bulk-testosterone-pre-workout:official"]),
      ],
      verification: "verified",
      reviewNotes: ["The guide discloses a 9,240 mg proprietary blend and 300 mg caffeine; other individual amounts are not disclosed."],
    },
    relationships: {
      commonlyComparedWith: ["bulk-apex-strength-pre-workout"],
      complements: ["l-citrulline-raw"],
      substitutes: ["bulk-apex-strength-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("bulk-testosterone-pre-workout", "bulk-strength-pre-workout", "site-images/bulk-testosterone-pre-workout-panel-bulk-side-2.png"),
    verification: "verified",
  },
  {
    productId: "bulk-apex-strength-pre-workout",
    shortName: "BULK APEX",
    aliases: ["bulk apex", "apex", "bulk apex strength"],
    purpose: "The premium BULK strength formula with disclosed creatine, HMB, betaine, and elevATP.",
    retailerPitch: "The stronger, premium BULK step-up for experienced strength-focused customers.",
    bestFor: ["A premium strength pre-workout", "Customers seeking 5 g creatine and 3 g HMB", "Experienced stimulant users"],
    notIdealFor: ["Stimulant-sensitive shoppers", "A lower-MAP strength SKU"],
    keyDifferentiators: ["5 g Creatine Monohydrate", "3 g Calcium HMB", "400 mg official total caffeine", "elevATP"],
    goals: ["strength", "energy", "recovery", "focus"],
    formula: {
      servingSize: "1 scoop (25.5 g)",
      servingsPerContainer: 20,
      totalCaffeineMg: 400,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Creatine Monohydrate", 5, "g", ["strength", "performance"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Beta-Alanine", 5, "g", ["performance"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Calcium HMB", 3, "g", ["strength", "recovery"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Betaine Anhydrous", 2.5, "g", ["strength", "performance"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Taurine", 2, "g", ["hydration", "performance"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("L-Tyrosine", 1, "g", ["focus"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Pink Himalayan Salt", 300, "mg", ["hydration", "mineral"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Bitter Orange Extract", 160, "mg", ["stimulant"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("elevATP", 150, "mg", ["strength", "performance"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("L-Theanine", 100, "mg", ["focus"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Mucuna Pruriens", 100, "mg", ["focus"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Dicaffeine Malate", 75, "mg", ["stimulant"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("Cafe Alatus", 50, "mg", ["stimulant"], ["bulk-apex-strength-pre-workout:label"]),
        ingredient("BioPerine", 5, "mg", ["other"], ["bulk-apex-strength-pre-workout:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["bulk-testosterone-pre-workout"],
      complements: ["pump-hyper-pump-pre-workout"],
      substitutes: ["bulk-testosterone-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("bulk-apex-strength-pre-workout", "bulk-apex-strength-pre-workout", "site-images/bulk-apex-strength-pre-workout-panel-bulkapex-sup-facts.png"),
    verification: "verified",
  },
  {
    productId: "bulk-pills-testosterone-capsules",
    shortName: "BULK PILLS",
    aliases: ["bulk pills", "bulk capsules", "testosterone pills"],
    purpose: "A capsule-format strength and testosterone-support product.",
    retailerPitch: "A convenient non-pre-workout strength-category add-on with the highest base MAP margin in the current portal.",
    bestFor: ["Capsule-format strength assortment", "Cross-selling beside BULK powder"],
    notIdealFor: ["A pre-workout energy request"],
    keyDifferentiators: ["No flavor decision", "30 servings", "Fadogia, Bulbine, Tongkat Ali, and Shilajit"],
    goals: ["strength", "recovery"],
    formula: {
      servingSize: "4 capsules",
      servingsPerContainer: 30,
      totalCaffeineMg: 0,
      caffeineServingBasis: "4 capsules",
      stimulantFree: true,
      ingredients: [
        ingredient("Vitamin D3", 125, "mcg", ["vitamin"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Magnesium", 30, "mg", ["mineral"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Zinc", 5.5, "mg", ["mineral"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Fadogia Agrestis", 500, "mg", ["strength"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Bulbine Natalensis", 500, "mg", ["strength"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Tongkat Ali", 400, "mg", ["strength"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Spilanthes Acmella", 300, "mg", ["strength"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Inositol", 200, "mg", ["other"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Shilajit", 100, "mg", ["strength"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("DIM", 100, "mg", ["other"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Black Pepper Extract", 10, "mg", ["other"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Boron Citrate", 10, "mg", ["mineral"], ["bulk-pills-testosterone-capsules:label"]),
        ingredient("Pregnenolone", 10, "mg", ["other"], ["bulk-pills-testosterone-capsules:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["bulk-testosterone-pre-workout"],
      complements: ["bulk-testosterone-pre-workout", "bulk-apex-strength-pre-workout"],
      substitutes: [],
    },
    prohibitedClaims,
    sources: sources("bulk-pills-testosterone-capsules", "bulk-testosterone-pills", "products/bulk-pills-testosterone-capsules-panel.png"),
    verification: "verified",
  },
  {
    productId: "beta-alanine-raw",
    shortName: "Beta-Alanine RAW",
    aliases: ["beta alanine", "beta alanine raw", "raw beta alanine"],
    commonMisspellings: ["beta alinine", "beta alanin"],
    purpose: "A single-ingredient, unflavored Beta-Alanine powder.",
    retailerPitch: "A simple, explainable 60-serving RAW product for stacking and ingredient-specific shoppers.",
    bestFor: ["Ingredient-specific shoppers", "Stacking", "An easy staff-training product"],
    notIdealFor: ["Customers who want a complete flavored pre-workout"],
    keyDifferentiators: ["3.2 g Beta-Alanine", "60 servings", "Single ingredient"],
    goals: ["performance", "strength", "daily"],
    formula: {
      servingSize: "1 scoop (3.2 g)",
      servingsPerContainer: 60,
      totalCaffeineMg: 0,
      caffeineServingBasis: "1 scoop",
      stimulantFree: true,
      ingredients: [ingredient("Beta-Alanine", 3.2, "g", ["performance"], ["beta-alanine-raw:label"])],
      warnings: ["The label notes that larger doses can cause a temporary tingling sensation."],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["creatine-monohydrate-raw", "l-citrulline-raw"],
      complements: ["creatine-monohydrate-raw", "l-citrulline-raw"],
      substitutes: [],
    },
    prohibitedClaims,
    sources: sources("beta-alanine-raw", "beta-alanine", "site-images/beta-alanine-raw-panel-beta-ingred.png"),
    verification: "verified",
  },
  {
    productId: "creatine-monohydrate-raw",
    shortName: "Creatine RAW",
    aliases: ["creatine", "creatine monohydrate", "creatine raw", "raw creatine"],
    commonMisspellings: ["creatine mono", "creatine monohydrat"],
    purpose: "A single-ingredient micronized Creatine Monohydrate powder.",
    retailerPitch: "A staple, easy-to-explain 60-serving RAW product with a $34.99 MAP.",
    bestFor: ["A foundational strength shelf", "Stacking", "Ingredient-specific shoppers"],
    notIdealFor: ["Customers who want a complete flavored pre-workout"],
    keyDifferentiators: ["5 g Creatine Monohydrate", "60 servings", "Single ingredient"],
    goals: ["strength", "recovery", "daily"],
    formula: {
      servingSize: "1 scoop (5 g)",
      servingsPerContainer: 60,
      totalCaffeineMg: 0,
      caffeineServingBasis: "1 scoop",
      stimulantFree: true,
      ingredients: [ingredient("Creatine Monohydrate", 5, "g", ["strength", "performance"], ["creatine-monohydrate-raw:label"])],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["beta-alanine-raw", "l-citrulline-raw"],
      complements: ["bulk-testosterone-pre-workout", "l-citrulline-raw"],
      substitutes: [],
    },
    prohibitedClaims,
    sources: sources("creatine-monohydrate-raw", "creatine", "site-images/creatine-monohydrate-raw-panel-creatine-ingred-aae1b4f5-c2bc-4635-9eba-1e1f66ef4734.png"),
    verification: "verified",
  },
  {
    productId: "fit-performance-pre-workout",
    shortName: "FIT",
    aliases: ["fit", "fit pre workout", "adrenolyn fit"],
    purpose: "A performance pre-workout positioned around endurance, power, focus, and moderate stimulant energy.",
    retailerPitch: "A balanced performance formula with 200 mg caffeine, creatine, Beta-Alanine, PeakO2, betaine, and Alpha GPC.",
    bestFor: ["A moderate-stimulant performance position", "Customers prioritizing endurance and power support"],
    notIdealFor: ["A stimulant-free request", "Customers seeking a currently orderable portal item"],
    keyDifferentiators: ["200 mg caffeine", "Endurance, power, and focus blend structure", "Creatine and PeakO2 positioning"],
    goals: ["energy", "focus", "strength", "performance"],
    formula: {
      totalCaffeineMg: 200,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Beta-Alanine", undefined, undefined, ["performance"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("PeakO2 Mushroom Blend", undefined, undefined, ["performance"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("BioPerine", undefined, undefined, ["other"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Creatine Monohydrate", undefined, undefined, ["strength", "performance"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Betaine Anhydrous", undefined, undefined, ["strength", "performance"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Alpha GPC 50%", undefined, undefined, ["focus"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Theobromine", undefined, undefined, ["stimulant"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Caffeine Anhydrous", 200, "mg", ["stimulant", "energy"], ["fit-performance-pre-workout:guide"]),
        ingredient("Mucuna Pruriens", undefined, undefined, ["focus"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Vitamin B12", undefined, undefined, ["vitamin"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Sodium Chloride", undefined, undefined, ["hydration", "mineral"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Potassium Chloride", undefined, undefined, ["hydration", "mineral"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
        ingredient("Trisodium Citrate", undefined, undefined, ["hydration", "mineral"], ["fit-performance-pre-workout:guide"], "listed-in-blend"),
      ],
      verification: "verified",
      reviewNotes: ["The guide lists blend totals, while individual amounts are disclosed only for caffeine."],
    },
    relationships: {
      commonlyComparedWith: ["underground-high-stimulant", "nootropic-high-focus-pre-workout"],
      complements: ["nitricoxide-stim-free-pre-workout"],
      substitutes: ["underground-high-stimulant"],
    },
    prohibitedClaims,
    sources: [{
      id: "fit-performance-pre-workout:guide",
      type: "product-guide",
      location: "BLACKMARKETLABS Pre-Workout Product Guide (2026-07-27), pages 10–11",
      note: "Owner-supplied authoritative product guide.",
    }],
    verification: "verified",
  },
  {
    productId: "nootropic-high-focus-pre-workout",
    shortName: "NOOTROPIC",
    aliases: ["nootropic", "nootropic high focus", "high focus pre workout"],
    commonMisspellings: ["no tropic", "nootrpic"],
    purpose: "A high-focus pre-workout positioned around cognitive support, energy, and pump.",
    retailerPitch: "The established $54.99 MAP focus formula for customers who want a recognizable nootropic-forward pre-workout.",
    bestFor: ["Focus-first pre-workout shoppers", "Customers seeking 350 mg caffeine"],
    notIdealFor: ["Stimulant-sensitive shoppers"],
    keyDifferentiators: ["350 mg caffeine anhydrous", "Lion's Mane and Alpha GPC positioning", "Four represented flavors"],
    goals: ["focus", "energy", "pump"],
    formula: {
      servingSize: "1 scoop",
      totalCaffeineMg: 350,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Beta-Alanine", 3200, "mg", ["performance"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("L-Citrulline", 3000, "mg", ["pump"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("L-Tyrosine", 1000, "mg", ["focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Lion's Mane", 600, "mg", ["focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Sodium Bicarbonate", 500, "mg", ["hydration", "performance"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Pink Himalayan Salt", 300, "mg", ["hydration", "mineral"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Alpha GPC 50%", 300, "mg", ["focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Dendrobium Extract 10:1", 300, "mg", ["stimulant", "focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Eria Jarensis", 125, "mg", ["stimulant", "focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Creatine Anhydrous", 100, "mg", ["strength", "performance"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("GABA", 100, "mg", ["focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Mucuna Pruriens", 70, "mg", ["focus"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("Caffeine Anhydrous", 350, "mg", ["stimulant"], ["nootropic-high-focus-pre-workout:guide"]),
        ingredient("AstraGin", 25, "mg", ["other"], ["nootropic-high-focus-pre-workout:guide"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["rule-hyper-focus", "bump-laser-focus-nootropic", "underground-high-stimulant"],
      complements: ["nitricoxide-stim-free-pre-workout"],
      substitutes: ["rule-hyper-focus", "bump-laser-focus-nootropic"],
    },
    prohibitedClaims,
    sources: sources("nootropic-high-focus-pre-workout", "nootropic-high-focus-pre-workout", "site-images/nootropic-high-focus-pre-workout-panel-nootr-final-side2.png"),
    verification: "verified",
  },
  {
    productId: "underground-high-stimulant",
    shortName: "UNDERGROUND",
    aliases: ["underground", "underground high stimulant", "high stim underground"],
    purpose: "A high-stimulant pre-workout with a broad disclosed focus and performance formula.",
    retailerPitch: "An established high-stim choice below the $59.99 hyper-formula MAP tier.",
    bestFor: ["Experienced stimulant users", "Customers seeking 300 mg caffeine and a full pre-workout"],
    notIdealFor: ["Stimulant-sensitive shoppers", "A daily low-stimulant request"],
    keyDifferentiators: ["300 mg caffeine", "7 g Citrulline Malate", "3.2 g Beta-Alanine", "$54.99 MAP"],
    goals: ["energy", "focus", "pump", "performance"],
    formula: {
      servingSize: "1 scoop (17.04 g)",
      servingsPerContainer: 25,
      totalCaffeineMg: 300,
      caffeineServingBasis: "1 scoop",
      stimulantFree: false,
      ingredients: [
        ingredient("Citrulline Malate", 7, "g", ["pump", "performance"], ["underground-high-stimulant:label"]),
        ingredient("Beta-Alanine", 3.2, "g", ["performance"], ["underground-high-stimulant:label"]),
        ingredient("L-Tyrosine", 1000, "mg", ["focus"], ["underground-high-stimulant:guide"]),
        ingredient("Dendrobium Extract", 800, "mg", ["stimulant", "focus"], ["underground-high-stimulant:guide"]),
        ingredient("Sodium Bicarbonate", 500, "mg", ["hydration", "performance"], ["underground-high-stimulant:guide"]),
        ingredient("Pink Himalayan Salt", 300, "mg", ["hydration", "mineral"], ["underground-high-stimulant:guide"]),
        ingredient("Alpha GPC", 300, "mg", ["focus"], ["underground-high-stimulant:label"]),
        ingredient("N-Acetyl L-Tyrosine", 250, "mg", ["focus"], ["underground-high-stimulant:label"]),
        ingredient("Choline Bitartrate", 200, "mg", ["focus"], ["underground-high-stimulant:label"]),
        ingredient("Eria Jarensis", 150, "mg", ["stimulant", "focus"], ["underground-high-stimulant:label"]),
        ingredient("Juniper Berry", 150, "mg", ["stimulant"], ["underground-high-stimulant:label"]),
        ingredient("Theobromine", 150, "mg", ["stimulant"], ["underground-high-stimulant:label"]),
        ingredient("L-Theanine", 150, "mg", ["focus"], ["underground-high-stimulant:label"]),
        ingredient("Mucuna Pruriens", 70, "mg", ["focus"], ["underground-high-stimulant:label"]),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["underground-high-stimulant:guide"]),
        ingredient("AstraGin", 25, "mg", ["other"], ["underground-high-stimulant:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["defy-hyper-stimulant", "nootropic-high-focus-pre-workout"],
      complements: ["nitricoxide-stim-free-pre-workout"],
      substitutes: ["defy-hyper-stimulant", "nootropic-high-focus-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("underground-high-stimulant", "underground-high-stimulant-pre-workout", "site-images/underground-high-stimulant-panel-under-final-side2.png"),
    verification: "verified",
  },
  {
    productId: "defy-hyper-stimulant",
    shortName: "DEFY",
    aliases: ["defy", "defy hyper", "defy hyper stimulant"],
    purpose: "A hyper-stimulant pre-workout positioned around intense energy, pump, and performance.",
    retailerPitch: "The hyper-energy side of the DEFY/RULE comparison, for experienced stimulant customers.",
    bestFor: ["Experienced stimulant users", "Customers prioritizing energy and a large disclosed pump formula"],
    notIdealFor: ["Stimulant-sensitive shoppers", "A daily low-stimulant request"],
    keyDifferentiators: ["450 mg official total caffeine at two scoops", "10 g L-Citrulline", "5 g Betaine", "Energy-first positioning"],
    goals: ["energy", "pump", "focus", "performance"],
    formula: {
      servingSize: "2 scoops (27.19 g); 1-scoop option also shown",
      servingsPerContainer: 20,
      totalCaffeineMg: 450,
      caffeineServingBasis: "2 scoops",
      stimulantFree: false,
      ingredients: [
        ingredient("L-Citrulline", 10, "g", ["pump", "performance"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Betaine Anhydrous", 5, "g", ["strength", "performance"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Beta-Alanine", 3.2, "g", ["performance"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("L-Tyrosine", 1, "g", ["focus"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Alpha GPC", 600, "mg", ["focus"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Choline Bitartrate", 600, "mg", ["focus"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Dendrobium Extract", 600, "mg", ["stimulant", "focus"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("N-Acetyl L-Tyrosine", 500, "mg", ["focus"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Caffeine Anhydrous", 300, "mg", ["stimulant"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Pink Himalayan Salt", 300, "mg", ["hydration", "mineral"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Eria Jarensis", 300, "mg", ["stimulant", "focus"], ["defy-hyper-stimulant:guide"], "exact", "2 scoops"),
        ingredient("Bitter Orange Extract", 120, "mg", ["stimulant"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Cafe Alatus", 100, "mg", ["stimulant"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("L-Theanine", 100, "mg", ["focus"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Dicaffeine Malate", 75, "mg", ["stimulant"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
        ingredient("Mucuna Pruriens", 150, "mg", ["focus"], ["defy-hyper-stimulant:guide"], "exact", "2 scoops"),
        ingredient("BioPerine", 5, "mg", ["other"], ["defy-hyper-stimulant:label"], "exact", "2 scoops"),
      ],
      verification: "verified",
      reviewNotes: ["Walter White Gummy Bear is sold out and hidden in the wholesale portal."],
    },
    relationships: {
      commonlyComparedWith: ["rule-hyper-focus", "underground-high-stimulant", "scorch-ultra-thermogenic"],
      complements: [],
      substitutes: ["rule-hyper-focus", "underground-high-stimulant"],
    },
    prohibitedClaims,
    sources: sources("defy-hyper-stimulant", "defy-hyper-stimulant-pre-workout", "site-images/defy-hyper-stimulant-panel-defy-razzmango-supfact.png"),
    verification: "verified",
  },
  {
    productId: "rule-hyper-focus",
    shortName: "RULE",
    aliases: ["rule", "rule hyper focus", "rule focus"],
    purpose: "A hyper-focus pre-workout positioned around concentrated nootropic support, controlled focus, energy, and performance.",
    retailerPitch: "The focus-first side of the DEFY/RULE comparison for experienced stimulant customers.",
    bestFor: ["Experienced stimulant users", "Customers prioritizing focus and nootropic ingredients"],
    notIdealFor: ["Stimulant-sensitive shoppers", "A daily low-stimulant request"],
    keyDifferentiators: ["485 mg official total caffeine at two scoops", "3 g L-Tyrosine", "Lion's Mane and Uridine", "Focus-first positioning"],
    goals: ["focus", "energy", "performance", "pump"],
    formula: {
      servingSize: "2 scoops; 1-scoop option also shown",
      servingsPerContainer: 20,
      totalCaffeineMg: 485,
      caffeineServingBasis: "2 scoops",
      stimulantFree: false,
      ingredients: [
        ingredient("L-Citrulline", 5, "g", ["pump", "performance"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Beta-Alanine", 5, "g", ["performance"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("L-Tyrosine", 3, "g", ["focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Lion's Mane", 800, "mg", ["focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Alpha GPC", 600, "mg", ["focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Dendrobium Extract", 300, "mg", ["stimulant", "focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Pink Himalayan Salt", 300, "mg", ["hydration", "mineral"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Uridine Monophosphate", 250, "mg", ["focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Theobromine", 200, "mg", ["stimulant"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Eria Jarensis", 150, "mg", ["stimulant", "focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Caffeine Anhydrous", 350, "mg", ["stimulant"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Cafe Alatus", 100, "mg", ["stimulant"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Mucuna Pruriens", 350, "mg", ["focus"], ["rule-hyper-focus:guide"], "exact", "2 scoops"),
        ingredient("L-Theanine", 100, "mg", ["focus"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("Bitter Orange Extract", 100, "mg", ["stimulant"], ["rule-hyper-focus:guide"], "exact", "2 scoops"),
        ingredient("Dicaffeine Malate", 50, "mg", ["stimulant"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
        ingredient("BioPerine", 5, "mg", ["other"], ["rule-hyper-focus:label"], "exact", "2 scoops"),
      ],
      verification: "verified",
      reviewNotes: ["Purge Pop is sold out. Dragon Punch is available per the portal owner; its formula image is stored in live content."],
    },
    relationships: {
      commonlyComparedWith: ["defy-hyper-stimulant", "nootropic-high-focus-pre-workout", "bump-laser-focus-nootropic"],
      complements: [],
      substitutes: ["defy-hyper-stimulant", "nootropic-high-focus-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("rule-hyper-focus", "rule-hyper-focus-pre-workout", "site-images/rule-hyper-focus-panel-rule-watlem-supfact.png"),
    verification: "verified",
  },
  {
    productId: "bump-laser-focus-nootropic",
    shortName: "BUMP",
    aliases: ["bump", "bump nootropic", "laser focus bump"],
    purpose: "A lower-stimulant nootropic drink positioned for work, gaming, and daily mental focus rather than a full high-stim pre-workout.",
    retailerPitch: "The approachable focus option for customers who do not want a 300–485 mg stimulant formula.",
    bestFor: ["Daily focus positioning", "A lower-stimulant alternative", "Work and gaming merchandising"],
    notIdealFor: ["Customers seeking a maximum-stimulant pre-workout", "Questions requiring a confirmed total-caffeine value until the label conflict is resolved"],
    keyDifferentiators: ["Nootropic-first daily positioning", "Lower-stimulant placement", "Two represented flavors"],
    goals: ["focus", "daily", "energy"],
    formula: {
      servingSize: "2 scoops; 1-scoop option also shown",
      servingsPerContainer: 20,
      stimulantFree: false,
      ingredients: [
        ingredient("L-Tyrosine", 4, "g", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Taurine", 2, "g", ["hydration", "performance"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Alpha GPC", 600, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Lion's Mane", 500, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("GABA", 500, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Uridine Monophosphate", 100, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("5-HTP", 100, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Caffeine Anhydrous", 80, "mg", ["stimulant"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Natural Caffeine", 80, "mg", ["stimulant"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("L-Theanine", 80, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("Bitter Orange Extract", 60, "mg", ["stimulant"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("PQQ", 20, "mg", ["focus"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
        ingredient("BioPerine", 5, "mg", ["other"], ["bump-laser-focus-nootropic:label"], "exact", "2 scoops"),
      ],
      verification: "needs-review",
      reviewNotes: ["The official page says 80 mg total caffeine, while the current two-scoop label appears to list 80 mg from each of two caffeine sources. The assistant will not state a confirmed total."],
    },
    relationships: {
      commonlyComparedWith: ["nootropic-high-focus-pre-workout", "rule-hyper-focus"],
      complements: ["cuts-heat-stim-free-thermogenic"],
      substitutes: ["nootropic-high-focus-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("bump-laser-focus-nootropic", "bump-laser-focus-nootropic", "site-images/bump-laser-focus-nootropic-panel-bump-raspman-ingred.jpg"),
    verification: "needs-review",
  },
  {
    productId: "nitricoxide-stim-free-pre-workout",
    shortName: "NITRICOXIDE",
    aliases: ["nitricoxide", "nitric oxide", "nitric oxide stim free", "nox"],
    commonMisspellings: ["nitricoxide", "nitric oxside"],
    purpose: "A stimulant-free pre-workout positioned around pump, endurance, and focus through citrulline and extract-based ingredients.",
    retailerPitch: "The more rounded stim-free pre-workout for stores that want pump plus focus and endurance positioning.",
    bestFor: ["Stimulant-free pre-workout requests", "Late-day training positioning", "Stacking with a stimulant product"],
    notIdealFor: ["Customers asking specifically for stimulant energy"],
    keyDifferentiators: ["5 g L-Citrulline", "PeakO2 and CitraPeak positioning", "No disclosed caffeine"],
    goals: ["pump", "focus", "performance", "stim-free"],
    formula: {
      servingSize: "1 scoop (12.73 g)",
      servingsPerContainer: 25,
      totalCaffeineMg: 0,
      caffeineServingBasis: "1 scoop",
      stimulantFree: true,
      ingredients: [
        ingredient("L-Citrulline", 5, "g", ["pump", "performance"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("Watermelon Juice Powder", 1, "g", ["pump"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("PeakO2 Mushroom Blend", 1, "g", ["performance"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("Dextrose", 1, "g", ["performance"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("L-Tyrosine", 1, "g", ["focus"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("Pink Himalayan Salt", 500, "mg", ["hydration", "mineral"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("CitraPeak", 200, "mg", ["pump"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("Pine Bark Extract", 180, "mg", ["pump"], ["nitricoxide-stim-free-pre-workout:label"]),
        ingredient("Ginkgo Biloba", 120, "mg", ["focus"], ["nitricoxide-stim-free-pre-workout:label"]),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["pump-hyper-pump-pre-workout", "cuts-pump-thermogenic-liquid-glycerol"],
      complements: ["underground-high-stimulant", "nootropic-high-focus-pre-workout"],
      substitutes: ["pump-hyper-pump-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("nitricoxide-stim-free-pre-workout", "nitricoxide-stim-free-pre-workout", "site-images/nitricoxide-stim-free-pre-workout-panel-nitric-strawlem-supfact.png"),
    verification: "verified",
  },
  {
    productId: "pump-hyper-pump-pre-workout",
    shortName: "PUMP",
    aliases: ["pump", "hyper pump", "pump pre workout"],
    purpose: "The strongest pump-specific, stimulant-free powder in the current line, built around citrulline and nitrates.",
    retailerPitch: "The premium pump formula for customers who want every active aimed at pump and power output.",
    bestFor: ["A dedicated pump product", "Stimulant-free requests", "Stacking with another pre-workout"],
    notIdealFor: ["Customers asking for stimulant energy"],
    keyDifferentiators: ["8 g L-Citrulline", "Nitrate-based pump ingredients", "Over 16 g actives at two scoops", "No disclosed caffeine"],
    goals: ["pump", "performance", "stim-free"],
    formula: {
      servingSize: "2 scoops; 1-scoop option also shown",
      servingsPerContainer: 20,
      totalCaffeineMg: 0,
      caffeineServingBasis: "2 scoops",
      stimulantFree: true,
      ingredients: [
        ingredient("L-Citrulline", 8, "g", ["pump", "performance"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
        ingredient("Betaine Anhydrous", 2.5, "g", ["strength", "performance"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
        ingredient("Taurine", 2, "g", ["hydration", "performance"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
        ingredient("Betaine Nitrate", 2, "g", ["pump"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
        ingredient("Arginine Nitrate", 1, "g", ["pump"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
        ingredient("Pink Himalayan Salt", 500, "mg", ["hydration", "mineral"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
        ingredient("BioPerine", 5, "mg", ["other"], ["pump-hyper-pump-pre-workout:label"], "exact", "2 scoops"),
      ],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["nitricoxide-stim-free-pre-workout", "cuts-pump-thermogenic-liquid-glycerol"],
      complements: ["defy-hyper-stimulant", "rule-hyper-focus"],
      substitutes: ["nitricoxide-stim-free-pre-workout"],
    },
    prohibitedClaims,
    sources: sources("pump-hyper-pump-pre-workout", "pump-hyper-pump-pre-workout", "site-images/pump-hyper-pump-pre-workout-panel-pump-ingredients.png"),
    verification: "verified",
  },
  {
    productId: "l-citrulline-raw",
    shortName: "L-Citrulline RAW",
    aliases: ["l citrulline", "citrulline", "citrulline raw", "raw citrulline"],
    commonMisspellings: ["l citraline", "citruline"],
    purpose: "A single-ingredient, unflavored L-Citrulline powder.",
    retailerPitch: "A simple 60-serving RAW pump product for stacking and ingredient-specific shoppers.",
    bestFor: ["Ingredient-specific shoppers", "Stacking", "An easy staff-training product"],
    notIdealFor: ["Customers who want a complete flavored pre-workout"],
    keyDifferentiators: ["5 g L-Citrulline", "60 servings", "Single ingredient"],
    goals: ["pump", "performance", "daily", "stim-free"],
    formula: {
      servingSize: "1 scoop (5 g)",
      servingsPerContainer: 60,
      totalCaffeineMg: 0,
      caffeineServingBasis: "1 scoop",
      stimulantFree: true,
      ingredients: [ingredient("L-Citrulline", 5, "g", ["pump", "performance"], ["l-citrulline-raw:label"])],
      verification: "verified",
    },
    relationships: {
      commonlyComparedWith: ["beta-alanine-raw", "creatine-monohydrate-raw"],
      complements: ["creatine-monohydrate-raw", "bulk-testosterone-pre-workout"],
      substitutes: [],
    },
    prohibitedClaims,
    sources: sources("l-citrulline-raw", "l-citrulline", "site-images/l-citrulline-raw-panel-citrulline-ingred.png"),
    verification: "verified",
  },
];

export const KNOWLEDGE_BY_PRODUCT_ID = new Map(PRODUCT_KNOWLEDGE.map((entry) => [entry.productId, entry]));
